name: golangtest-ci

on: pull_request

jobs:
  golangci:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: git
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run Tests
        run: go test -v ./...