name: golangtest-ci

on: pull_request

jobs:
  golangci:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run Tests
        run: go get && go test -v ./...